### ISSUE TITLE
afkはtpで動かせる

### ISSUE THREAD

**Issue by kinoko2k** [seichi915Network/seichi915AFK#3]
afkはtpで動かせるのは、意味がない気が(よくtpする人いるし)(放置してるところが、作業中ならば、tpされたときに戻るのが大変な気がする)

**Comment by stouma915** [comment]
tpは運営しか使えませんので問題ではないのでは

**Comment by kinoko2k** [comment]
運営が使う場合を考えて

**Comment by stouma915** [comment]
AFK中に動けなくなるのは、AFK中は無敵なので無敵の状態を悪用しないためのもので、一般のプレイヤーをTPする機会なんてメンテナンスか何かの時ぐらいでは

**Comment by kinoko2k** [comment]
なるほど
