### ISSUE TITLE
ピストンで人を押せる

### ISSUE THREAD

**Issue by kinoko2k** [seichi915Network/seichi915AFK#4]
整地鯖・生活鯖では、afkした相手を、ピストンで押せます。

試験用動画
https://youtu.be/1fV89YaYj78
※この動画は、確認次第、非公開にします。

**Comment by kinoko2k** [comment]
生活鯖では、自分を犠牲にして、確認しました

**Comment by stouma915** [comment]
AFK中のプレイヤーが動けないのは、AFK中は無敵であるからです
プレイヤー自身がピストンを動かそうとするとAFKが解除されますし、他のプレイヤーと協力するにしても普通にやった方が早いのではとなります

**Comment by kinoko2k** [comment]
わかった
